### ISSUE TITLE
Not working on ST3 3114

### ISSUE THREAD

**Issue by amokwao** [bsoun/bang-search#2]
Hi,
 I was looking for a plugin like this but cannot get it to work. when i type the search item into the input panel and select the search engine nothing happens. Neither the keyboard shortcut for selected term nor the context menu works. Any ideas on making it work on ST version 3114?
Thank you,

**Comment by bsoun** [comment]
Hi,
Do you see the list of bang in the quick panel ? 
Which OS are you using ?
Could you paste the result of the following command executed in the View>Show console ?
`import webbrowser; print(webbrowser._browsers)`

**Comment by amokwao** [comment]
> Do you see the list of bang in the quick panel ? 

Yes and i am able to types the search item in and choose the engine I want

> Which OS are you using ?

I am on windows 10 

> Could you paste the result of the following command executed in the View>Show console ?
> import webbrowser; print(webbrowser._browsers)

 `{'windows-default': [<class 'webbrowser.WindowsDefault'>, None], 'c:\\program files\\internet explorer\\iexplore.exe': [None, <webbrowser.BackgroundBrowser object at 0x000001E692A7F320>]}`

I have chrome set as default on the computer but do not see that in the command output.
Thank you

**Comment by bsoun** [comment]
You should try to  Register chrome like suggested [here](https://github.com/bsoun/bang-search#register-a-browser-in-webbrowserpy) with the correct path and then [define](https://github.com/bsoun/bang-search#choose-the-browser-for-bang-search) it in the config file.
I'm not able to test in W10, but in W7 it does the trick.

**Comment by amokwao** [comment]
thank  you. i followed those setup instruction but same results. i am thinking maybe because I am using ST portable. thanks for you help
