### ISSUE TITLE
[Bug] Not working personal keys

### ISSUE THREAD

**Issue by Kristinita** [bsoun/bang-search#3]
### 1. Summary

Personal keys not working for me. I get stack trace in console.

### 2. Expected behavior

Successful open my search queries in browser, if I make hotkeys for separate sites.

### 3. Actual behavior

```python
Traceback (most recent call last):
  File "E:\Sublime Text 3\Data\Packages\Bang Search\bang-search.py", line 148, in direct_done
    searchByBang(self.stringToSearch,self.bangToSearch,self.choosedBrowser)
TypeError: searchByBang() missing 1 required positional argument: 'choosedBrowser'
```

### 4. Settings

Part of my `User/bang_search.sublime-settings` file:

```json
{
"browsers_list": ["default", "google-chrome"],
"definitions": {
    "!github": {
        "type": "duckduckgo",
        "caption": "GitHub"
        },
    }
}
```

Part of my `User/Default (Windows).sublime-keymap` like in [**README.MD**](https://github.com/bsoun/bang-search#usage):

```json
{
  "keys": ["ctrl+super+b"],
  "command": "bang_search_input",
  "args": {"search_method": "!github"}
},
```

### 5. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install Bang Search via Package Control → I restart Sublime Text → I set Bang Search.

I run `bang_search_input {}` command → I print my search query → <kbd>Enter</kbd> → I select `!github` in my quick panel → <kbd>Enter</kbd> → correct link successfully open for me.

I press <kbd>Ctrl+Super+B</kbd> → I print my search query → <kbd>Enter</kbd> → I get stack trace, no links open for me.

### 6. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by bsoun** [comment]
Thank you for your detailed explanation. A new version will be push soon.
